services:
  - type: web
    name: blitzapp
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false; blitz db migrate; blitz build
    startCommand: blitz start --production
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        value: https://blitz-jobs.com/
      - key: MAIL_DRIVER
        value: SENDGRID
      - key: MAIL_SENDGRID_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: blitzapp-db
          property: connectionString
databases:
  - name: blitzapp-db
    plan: starter
